### ISSUE TITLE
docker compose up gui command resulting in react-scripts: not found error 

### ISSUE THREAD

**Issue by gs7vik** [EpistasisLab/KRAGEN#97]
**Describe the bug**
After following the steps mentioned in the readme.md file, docker compose up gui gives the following error:
kragen-gui  | sh: 1: react-scripts: not found
kragen-gui exited with code 127

**To Reproduce**
1. Clone the main branch of github repo.
2. after running the initial 7 steps from readme.md file and when you try to boot up the UI using docker compose up gui(the 8th step)
4. You can see the react-scripts not found error 

**Expected behavior**
To able to use the UI on http://localhost:3000/ to ask the user queries.

**Screenshots**
![image](https://github.com/EpistasisLab/KRAGEN/assets/57762136/440c0c33-71c7-490a-8b3b-18d7899371be)

**Desktop (please complete the following information):**
 - OS: windows 10 x64
 
 -docker version: 24.0.2, build cb74dfc
**Additional context**
I am using weaviate cloud instance and had set up the url and have set up the api key correctly in the .env file. And there is no error while ingesting the data into the vector db.

**Comment by jay-m-dev** [comment]
KRAGEN is not yet supported on Windows. But it will work on WSL 2 (It was tested using Ubuntu on WSL 2)

**Comment by zhixwang** [comment]
Same here. I got the same error for both Mac and WSL.

**Comment by jay-m-dev** [comment]
Thank you @gs7vik and @zhixwang for reporting this bug.
This was fixed by #98.
Please try again.

**Comment by jay-m-dev** [comment]
The KRAGEN_Dashboard/Backend/config.json file is updated by Step 7 of the [Installation Instructions](https://github.com/EpistasisLab/KRAGEN?tab=readme-ov-file#installation).
If step 7 is skipped (e.g. a Weaviate vector DB is already configured), then the steps in [Reconfiguring the Backend](https://github.com/EpistasisLab/KRAGEN?tab=readme-ov-file#reconfiguring-the-backend) should solve this problem.
The readme file will be revised soon to make this clearer.

Thank you!
